# tmp/showcase/gen_configs.py
"""Generate tmp/configs/*.yaml for each showcase milestone, copying config.yaml's
world: block VERBATIM so every config shares the current world hash.

Run from repo root:
    python tmp/showcase/gen_configs.py            # full-fidelity (committed set)
    python tmp/showcase/gen_configs.py --fast     # quick: capped iters + 1 seed

--fast OVERWRITES the same files with throwaway quick configs; restore the committed
set with `git checkout -- tmp/configs` or by re-running without --fast."""
from __future__ import annotations

import argparse
import copy
import os
import sys


REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

import yaml

from milestones import MILESTONES


BASE_CONFIG_PATH = os.path.join(REPO_ROOT, 'config.yaml')
CONFIGS_DIR = os.path.join(REPO_ROOT, 'tmp', 'configs')
FAST_ITERS = 60
FAST_SEEDS = [0]


def _loadBaseRaw():
    with open(BASE_CONFIG_PATH, 'r', encoding='utf-8') as a:
        return yaml.safe_load(a) or {}


def buildConfigDict(milestone, baseRaw, isFast=False):
    """Return a complete config dict = baseRaw with the milestone's reward/training/
    curriculum deltas applied. world: is copied verbatim (guarantees hash identity)."""
    raw = copy.deepcopy(baseRaw)
    raw['reward'].update(milestone['reward'])
    raw['training'].update(milestone['training'])
    stageByName = {stage['name']: stage for stage in baseRaw['curriculum']['stages']}
    stages = [copy.deepcopy(stageByName[name]) for name in milestone['stages']]
    if milestone['fullOverride']:
        for stage in stages:
            if stage['name'] == 'full':
                stage.update(milestone['fullOverride'])
    raw['curriculum']['stages'] = stages
    if isFast:
        raw['training']['totalIters'] = FAST_ITERS
        raw['training']['evalSeeds'] = list(FAST_SEEDS)
    return raw


def _header(milestone, isFast):
    tag = '  [FAST: capped iters / 1 seed]' if isFast else ''
    return (
        f"# GENERATED by tmp/showcase/gen_configs.py — DO NOT hand-edit.{tag}\n"
        f"# Milestone: {milestone['name']}  ({milestone['fidelity']})\n"
        f"# Source: {milestone['source']}\n"
        f"# Note: {milestone['note']}\n"
        f"# world: copied verbatim from config.yaml (shares the current world hash).\n"
    )


def generateAll(outDir=CONFIGS_DIR, isFast=False):
    """Write every milestone's yaml into outDir; return the paths written."""
    os.makedirs(outDir, exist_ok=True)
    baseRaw = _loadBaseRaw()
    paths = []
    for milestone in MILESTONES:
        raw = buildConfigDict(milestone, baseRaw, isFast=isFast)
        path = os.path.join(outDir, milestone['file'])
        with open(path, 'w', encoding='utf-8') as a:
            a.write(_header(milestone, isFast))
            yaml.safe_dump(raw, a, sort_keys=False, default_flow_style=None)
        paths.append(path)
        print(f"wrote {path}")
    return paths


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--fast', action='store_true', help='cap iters + single seed for quick models')
    args = parser.parse_args()
    generateAll(isFast=args.fast)


if __name__ == '__main__':
    main()
